# Generated by Django 3.1.2 on 2022-01-03 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('date_creaction', models.DateField(auto_now_add=True, verbose_name='Date of Creation')),
                ('date_modify', models.DateField(auto_now=True, verbose_name='Date of Modify')),
                ('date_delete', models.DateField(auto_now=True, verbose_name='Date of Delete')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=120, verbose_name='Last name')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='email')),
                ('description', models.TextField(verbose_name='Description')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Image')),
                ('github', models.URLField(blank=True, null=True, verbose_name='Github')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('date_modify', models.DateField(auto_now=True, verbose_name='Date of Modify')),
                ('date_delete', models.DateField(auto_now=True, verbose_name='Date of Delete')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='description')),
                ('GitLink', models.URLField(blank=True, null=True, verbose_name='Github repository')),
                ('YoutubeLink', models.URLField(blank=True, null=True, verbose_name='Youtube')),
                ('PythonanywhereLink', models.URLField(blank=True, null=True, verbose_name='Pythonanywhere')),
                ('image', models.ImageField(max_length=255, upload_to='projects/', verbose_name='Image')),
                ('date_creaction', models.DateField(verbose_name='Date of Creation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasePortfolio.author')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
