# Generated by Django 3.1.2 on 2022-01-04 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0002_auto_20220103_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('date_creaction', models.DateField(auto_now_add=True, verbose_name='Date of Creation')),
                ('date_modify', models.DateField(auto_now=True, verbose_name='Date of Modify')),
                ('date_delete', models.DateField(auto_now=True, verbose_name='Date of Delete')),
                ('acronym', models.CharField(max_length=10, unique=True, verbose_name='Acronym')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BasePortfolio.language'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='language',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BasePortfolio.language'),
        ),
    ]
