# Generated by Django 3.1.2 on 2022-01-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0007_auto_20220105_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_creaction_project',
            field=models.DateField(default='', verbose_name='Date of Creation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_creaction',
            field=models.DateField(auto_now_add=True, verbose_name='Date of Creation'),
        ),
    ]
