# Generated by Django 3.1.2 on 2022-01-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0009_auto_20220105_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_creaction_project',
            field=models.DateField(default='2022-01-01', verbose_name='Date of Creation'),
        ),
    ]
