# Generated by Django 3.1.2 on 2022-01-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0012_auto_20220105_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_creaction_project',
            field=models.DateField(default=0, verbose_name='Date of Creation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='date_creaction',
            field=models.DateField(auto_now_add=True, verbose_name='Date of Creation'),
        ),
    ]
