# Generated by Django 3.1.2 on 2022-01-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0017_auto_20220105_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='PythonanywhereLink',
            new_name='LinkWeb',
        ),
    ]
