# Generated by Django 3.1.2 on 2022-01-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0018_auto_20220105_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='LinkWeb',
            field=models.URLField(blank=True, null=True, verbose_name='Link Web'),
        ),
    ]
