# Generated by Django 3.1.2 on 2022-01-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0019_auto_20220105_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='PythonanywhereLink',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='LinkWeb',
            field=models.URLField(blank=True, null=True, verbose_name='Link Web'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='date_creaction_tutorial',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Creation'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='date_creaction',
            field=models.DateField(auto_now_add=True, verbose_name='Date of Creation'),
        ),
    ]
