# Generated by Django 3.1.2 on 2022-01-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0020_auto_20220105_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('date_creaction', models.DateField(auto_now_add=True, verbose_name='Date of Creation')),
                ('date_modify', models.DateField(auto_now=True, verbose_name='Date of Modify')),
                ('date_delete', models.DateField(auto_now=True, verbose_name='Date of Delete')),
                ('titlepdf', models.CharField(blank=True, max_length=255, verbose_name='Title pdf')),
                ('namePdf', models.FileField(upload_to='documents/', verbose_name='Pdf')),
                ('date_updatePdf', models.DateTimeField(blank=True, null=True, verbose_name='Date of Creation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasePortfolio.author')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasePortfolio.language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
