# Generated by Django 3.1.2 on 2022-01-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0021_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdf',
            options={'verbose_name': 'pdf', 'verbose_name_plural': 'pdfs'},
        ),
    ]
