# Generated by Django 3.1.2 on 2022-01-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0023_auto_20220106_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='slug',
            field=models.CharField(default=0, max_length=150, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
