# Generated by Django 3.1.2 on 2022-04-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0024_pdf_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='information'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='information'),
        ),
    ]
