# Generated by Django 3.1.2 on 2022-04-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0025_auto_20220412_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='slug',
            new_name='slugT',
        ),
    ]
