# Generated by Django 3.1.2 on 2022-04-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0026_auto_20220413_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='slugT',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Slug'),
        ),
    ]
