# Generated by Django 3.1.2 on 2022-04-27 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0027_auto_20220413_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('date_creaction', models.DateField(auto_now_add=True, verbose_name='Date of Creation')),
                ('date_modify', models.DateField(auto_now=True, verbose_name='Date of Modify')),
                ('date_delete', models.DateField(auto_now=True, verbose_name='Date of Delete')),
                ('titleCompany', models.CharField(max_length=150, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('titleJob', models.CharField(max_length=150, verbose_name='TitleJob')),
                ('descriptionJob', models.TextField(verbose_name='TitleJob')),
                ('beginJob', models.CharField(max_length=150, verbose_name='BeginJob')),
                ('endJob', models.CharField(max_length=150, verbose_name='EndJob')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasePortfolio.language')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
            },
        ),
    ]
