# Generated by Django 3.1.2 on 2022-04-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0028_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='titleCompany',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
