# Generated by Django 3.1.2 on 2022-04-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0030_auto_20220427_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='date_creaction_job',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Creation'),
        ),
    ]
