# Generated by Django 3.1.2 on 2022-04-28 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0031_jobs_date_creaction_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='institutionsCertifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('date_creaction', models.DateField(auto_now_add=True, verbose_name='Date of Creation')),
                ('date_modify', models.DateField(auto_now=True, verbose_name='Date of Modify')),
                ('date_delete', models.DateField(auto_now=True, verbose_name='Date of Delete')),
                ('nameInstitute', models.CharField(max_length=150, unique=True, verbose_name='Name Institute')),
                ('imageInstitute', models.ImageField(max_length=255, null=True, upload_to='institute/', verbose_name='Image institute')),
            ],
            options={
                'verbose_name': 'institute',
                'verbose_name_plural': 'institutions',
            },
        ),
        migrations.CreateModel(
            name='educations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('date_creaction', models.DateField(auto_now_add=True, verbose_name='Date of Creation')),
                ('date_modify', models.DateField(auto_now=True, verbose_name='Date of Modify')),
                ('date_delete', models.DateField(auto_now=True, verbose_name='Date of Delete')),
                ('nameCollege', models.CharField(max_length=150, verbose_name='Name College')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('titleEducations', models.CharField(max_length=150, verbose_name='Title Education')),
                ('beginEducation', models.CharField(max_length=150, verbose_name='Begin Education')),
                ('endEducation', models.CharField(max_length=150, verbose_name='End Education')),
                ('date_creaction_education', models.DateField(blank=True, null=True, verbose_name='Date of Creation')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasePortfolio.language')),
            ],
            options={
                'verbose_name': 'education',
                'verbose_name_plural': 'educations',
            },
        ),
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('date_creaction', models.DateField(auto_now_add=True, verbose_name='Date of Creation')),
                ('date_modify', models.DateField(auto_now=True, verbose_name='Date of Modify')),
                ('date_delete', models.DateField(auto_now=True, verbose_name='Date of Delete')),
                ('titleCertification', models.CharField(max_length=150, verbose_name='Title Certifications')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasePortfolio.institutionscertifications')),
            ],
            options={
                'verbose_name': 'certification',
                'verbose_name_plural': 'certifications',
            },
        ),
    ]
