# Generated by Django 3.1.2 on 2022-04-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0032_certification_educations_institutionscertifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='LinkCertification',
            field=models.URLField(blank=True, null=True, verbose_name='Link Certifications'),
        ),
    ]
