# Generated by Django 3.1.2 on 2022-10-01 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0033_certification_linkcertification'),
    ]

    operations = [
        migrations.CreateModel(
            name='skillSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('date_creaction', models.DateField(auto_now_add=True, verbose_name='Date of Creation')),
                ('date_modify', models.DateField(auto_now=True, verbose_name='Date of Modify')),
                ('date_delete', models.DateField(auto_now=True, verbose_name='Date of Delete')),
                ('nameSkillSection', models.CharField(max_length=150, unique=True, verbose_name='Name Skill Section')),
            ],
            options={
                'verbose_name': 'skillSection',
                'verbose_name_plural': 'skillSection',
            },
        ),
        migrations.CreateModel(
            name='skillName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('date_creaction', models.DateField(auto_now_add=True, verbose_name='Date of Creation')),
                ('date_modify', models.DateField(auto_now=True, verbose_name='Date of Modify')),
                ('date_delete', models.DateField(auto_now=True, verbose_name='Date of Delete')),
                ('nameSkill', models.CharField(max_length=150, unique=True, verbose_name='Name Skill')),
                ('numberSkill', models.IntegerField(verbose_name='Number skill')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasePortfolio.institutionscertifications')),
            ],
            options={
                'verbose_name': 'skillSection',
                'verbose_name_plural': 'skillSection',
            },
        ),
    ]
