# Generated by Django 3.1.2 on 2022-10-01 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0034_skillname_skillsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillname',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasePortfolio.skillsection'),
        ),
    ]
