# Generated by Django 3.1.2 on 2022-10-01 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0035_auto_20221001_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillname',
            old_name='institute',
            new_name='nameSkillSection',
        ),
    ]
