# Generated by Django 3.1.2 on 2022-10-01 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0036_auto_20221001_0216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillname',
            options={'verbose_name': 'SkillName', 'verbose_name_plural': 'SkillNames'},
        ),
        migrations.AlterModelOptions(
            name='skillsection',
            options={'verbose_name': 'skillSection', 'verbose_name_plural': 'skillSections'},
        ),
    ]
