# Generated by Django 3.1.2 on 2022-10-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasePortfolio', '0037_auto_20221001_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillname',
            name='nameSkill',
            field=models.CharField(max_length=150, verbose_name='Name Skill'),
        ),
    ]
